//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace greenguard_hub.Resources
{
    
    internal partial class Views
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Views.manager == null))
                {
                    Views.manager = new System.Resources.ResourceManager("greenguard_hub.Resources.Views", typeof(Views).Assembly);
                }
                return Views.manager;
            }
        }
        internal static byte[] GetBytes(Views.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            Success = -5078,
            Error = 26796,
            Style = 27194,
            Index = 30232,
        }
    }
}
